# Java makefile

# Utilities
#===============================================================================
help:
	@echo "Makefile options:"
	@echo "	make help: shows this help"
	@echo "	make check: checks for marks on the code"

check: ./utilities/check
	@./utilities/check
