# Ruby makefile

# Utilities
#===============================================================================
help:
		@echo "Ruby makefile options:"
		@echo "	make help: shows this information"
		@echo "	make check: checks for marks on the code"
check: ./utilities/check
		@./utilities/check
