# Ruby makefile

# Utilities
#===============================================================================
help:
		@echo "Ruby makefile options:"
		@echo "	make help: shows this information"
		@echo "	make check: checks for marks on the code"
check: ./utilities/check
		@./utilities/check
test: ./test/test_p1.rb
		@echo "Running game test!"
		@./test/test_p1.rb
