/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import ControllerDeprecated.Controller;
import deepspace.DamageToUI;
import deepspace.HangarToUI;
import deepspace.ShieldToUI;
import deepspace.SpaceStationToUI;
import deepspace.WeaponToUI;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel Ángel Fernández Gutiérrez, Sergio Quijano Rey
 */
public class CurrentStationView extends javax.swing.JPanel {

    private HangarPanel currentHangarPanel;
    private ShieldPanel currentShieldPanel;
    private WeaponPanel currentWeaponPanel;
    
    /**
     * Creates new form CurrentStationView
     */
    public CurrentStationView() {
        initComponents();
        
        currentWeaponPanel = new WeaponPanel();
        currentShieldPanel = new ShieldPanel();
        currentHangarPanel = new HangarPanel();
        
        jpWeapon.add(currentWeaponPanel);
        jpShield.add(currentShieldPanel);
        jpHangar.add(currentHangarPanel);
    }
    
    SpaceStationToUI station;
    
    void setStation(SpaceStationToUI st) {
        System.out.println("Setting station...");
        station = st;
        jlAmmoPower.setText(Float.toString(station.getAmmoPower()));
        jlFuelUnits.setText(Float.toString(station.getFuelUnits()));
        jlNMedals.setText(Integer.toString(station.getnMedals()));
        jlName.setText(station.getName());
        jlShieldPower.setText(Float.toString(station.getShieldPower()));
        
        currentWeaponPanel.setWeapon(station);
        currentShieldPanel.setShield(station);
        currentHangarPanel.setHangar(station.getHangar());
                
        DamageToUI damage = station.getPendingDamage();
        if ( damage != null ) {
            jlDamageShields.setText(Integer.toString(damage.getNShields()));
            jlDamageWeapons.setText(damage.getWeaponInfo());
        } else {
            jlDamageShields.setText("");
            jlDamageWeapons.setText("");
        }     
        
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedWeapons() {
        return currentWeaponPanel.getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedShieldBoosters() {
        return currentShieldPanel.getSelectedShieldBoosters();
    }
    
    ArrayList<Integer> getSelectedWeaponsInHangar() {
        return currentHangarPanel.getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedShieldBoostersInHangar() {
        return currentHangarPanel.getSelectedShieldBoosters();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlName = new javax.swing.JLabel();
        jlAmmoPowerLabel = new javax.swing.JLabel();
        jlShieldPowerLabel = new javax.swing.JLabel();
        jlFuelUnitsLabel = new javax.swing.JLabel();
        jlNMedalsLabel = new javax.swing.JLabel();
        jlAmmoPower = new javax.swing.JLabel();
        jlShieldPower = new javax.swing.JLabel();
        jlFuelUnits = new javax.swing.JLabel();
        jlNMedals = new javax.swing.JLabel();
        jpPendingDamage = new javax.swing.JPanel();
        jlDamageShieldsLabel = new javax.swing.JLabel();
        jlDamageWeaponsLabel = new javax.swing.JLabel();
        jlDamageShields = new javax.swing.JLabel();
        jlDamageWeapons = new javax.swing.JLabel();
        jpWeapon = new javax.swing.JPanel();
        jpShield = new javax.swing.JPanel();
        jpHangar = new javax.swing.JPanel();

        jlName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlName.setText("name");

        jlAmmoPowerLabel.setText("Potencia de ataque");

        jlShieldPowerLabel.setText("Potencia de defensa");

        jlFuelUnitsLabel.setText("Nivel de combustible");

        jlNMedalsLabel.setText("Medallas");

        jlAmmoPower.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlAmmoPower.setText("ammoPower");

        jlShieldPower.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlShieldPower.setText("shieldPower");

        jlFuelUnits.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlFuelUnits.setText("fuelUnits");

        jlNMedals.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlNMedals.setText("nMedals");

        jpPendingDamage.setBorder(javax.swing.BorderFactory.createTitledBorder("Castigo pendiente"));

        jlDamageShieldsLabel.setText("Escudos");

        jlDamageWeaponsLabel.setText("Armas");

        jlDamageShields.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlDamageShields.setText("sh");

        jlDamageWeapons.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlDamageWeapons.setText("we");

        javax.swing.GroupLayout jpPendingDamageLayout = new javax.swing.GroupLayout(jpPendingDamage);
        jpPendingDamage.setLayout(jpPendingDamageLayout);
        jpPendingDamageLayout.setHorizontalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDamageShieldsLabel)
                    .addComponent(jlDamageWeaponsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDamageWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jlDamageShields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPendingDamageLayout.setVerticalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDamageShieldsLabel)
                    .addComponent(jlDamageShields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDamageWeaponsLabel)
                    .addComponent(jlDamageWeapons))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jpWeapon.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de fuego"));

        jpShield.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de defensa"));

        jpHangar.setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHangar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAmmoPowerLabel)
                                    .addComponent(jlShieldPowerLabel)
                                    .addComponent(jlFuelUnitsLabel)
                                    .addComponent(jlNMedalsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlFuelUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlShieldPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlAmmoPower, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jlNMedals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpShield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAmmoPowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlShieldPowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlFuelUnitsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNMedalsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAmmoPower)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlShieldPower)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlFuelUnits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNMedals))))
                    .addComponent(jpPendingDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpShield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHangar, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAmmoPower;
    private javax.swing.JLabel jlAmmoPowerLabel;
    private javax.swing.JLabel jlDamageShields;
    private javax.swing.JLabel jlDamageShieldsLabel;
    private javax.swing.JLabel jlDamageWeapons;
    private javax.swing.JLabel jlDamageWeaponsLabel;
    private javax.swing.JLabel jlFuelUnits;
    private javax.swing.JLabel jlFuelUnitsLabel;
    private javax.swing.JLabel jlNMedals;
    private javax.swing.JLabel jlNMedalsLabel;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlShieldPower;
    private javax.swing.JLabel jlShieldPowerLabel;
    private javax.swing.JPanel jpHangar;
    private javax.swing.JPanel jpPendingDamage;
    private javax.swing.JPanel jpShield;
    private javax.swing.JPanel jpWeapon;
    // End of variables declaration//GEN-END:variables
}
